// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANeTcAHjOgd5_9Cstiwv4PrJCakM9qSjo',
    appId: '1:309381550140:web:3e549c5a6405fc23217339',
    messagingSenderId: '309381550140',
    projectId: 'signuphospital',
    authDomain: 'signuphospital.firebaseapp.com',
    storageBucket: 'signuphospital.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAubfoD5Ki02IdXOFo6T0UktFyf7mN-hBA',
    appId: '1:309381550140:android:170df1b0ed55be1d217339',
    messagingSenderId: '309381550140',
    projectId: 'signuphospital',
    storageBucket: 'signuphospital.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH_ZAdcsgtseuwC6HmqgO9GrX-Tf_4YTw',
    appId: '1:309381550140:ios:9a3891f280fde28e217339',
    messagingSenderId: '309381550140',
    projectId: 'signuphospital',
    storageBucket: 'signuphospital.firebasestorage.app',
    iosBundleId: 'com.example.untitled6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDH_ZAdcsgtseuwC6HmqgO9GrX-Tf_4YTw',
    appId: '1:309381550140:ios:9a3891f280fde28e217339',
    messagingSenderId: '309381550140',
    projectId: 'signuphospital',
    storageBucket: 'signuphospital.firebasestorage.app',
    iosBundleId: 'com.example.untitled6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANeTcAHjOgd5_9Cstiwv4PrJCakM9qSjo',
    appId: '1:309381550140:web:246f2a10eb4543cb217339',
    messagingSenderId: '309381550140',
    projectId: 'signuphospital',
    authDomain: 'signuphospital.firebaseapp.com',
    storageBucket: 'signuphospital.firebasestorage.app',
  );
}
